version: '3'
services:
  db:
    image: mysql:5.7
    container_name: database_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user_db
      MYSQL_PASSWORD: password1
    volumes:
      - vol-db-data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: pma_container
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
volumes:
  vol-db-data:
